// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aonmwpdfxnzyuaaihkcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbm13cGRmeG56eXVhYWloa2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Njc0OTMsImV4cCI6MjA2NzM0MzQ5M30.iI0z4socsEpggWgd9ujr5KcCMDOk853Wh3I-wCNUQIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});